/**
 * Official brand color per technology icon key (matches the keys in
 * `technologyIcons.ts`), sourced from the Simple Icons dataset that backs
 * `react-icons/si`. `iconTone` says whether the icon/text drawn on top of
 * `hex` should be light or dark to stay legible.
 */
export interface TechnologyBrandColor {
  hex: string
  iconTone: 'light' | 'dark'
}

export const technologyBrandColors: Record<string, TechnologyBrandColor> = {
  javascript: { hex: '#F7DF1E', iconTone: 'dark' },
  typescript: { hex: '#3178C6', iconTone: 'light' },
  html5: { hex: '#E34F26', iconTone: 'light' },
  css3: { hex: '#1572B6', iconTone: 'light' },
  react: { hex: '#61DAFB', iconTone: 'dark' },
  vue: { hex: '#4FC08D', iconTone: 'light' },
  angular: { hex: '#0F0F11', iconTone: 'light' },
  node: { hex: '#5FA04E', iconTone: 'light' },
  python: { hex: '#3776AB', iconTone: 'light' },
  docker: { hex: '#2496ED', iconTone: 'light' },
  git: { hex: '#F03C2E', iconTone: 'light' },
  github: { hex: '#181717', iconTone: 'light' },
  postgresql: { hex: '#4169E1', iconTone: 'light' },
  mongodb: { hex: '#47A248', iconTone: 'light' },
  tailwind: { hex: '#06B6D4', iconTone: 'light' },
  nextjs: { hex: '#000000', iconTone: 'light' },
  vite: { hex: '#9135FF', iconTone: 'light' },
  svelte: { hex: '#FF3E00', iconTone: 'light' },
  solid: { hex: '#2C4F7C', iconTone: 'light' },
  astro: { hex: '#BC52EE', iconTone: 'light' },
  remix: { hex: '#000000', iconTone: 'light' },
  nuxt: { hex: '#00DC82', iconTone: 'light' },
  nestjs: { hex: '#E0234E', iconTone: 'light' },
  express: { hex: '#0A0A0A', iconTone: 'light' },
  django: { hex: '#092E20', iconTone: 'light' },
  flask: { hex: '#3BABC3', iconTone: 'light' },
  fastapi: { hex: '#009688', iconTone: 'light' },
  ruby: { hex: '#CC342D', iconTone: 'light' },
  rails: { hex: '#D30001', iconTone: 'light' },
  php: { hex: '#777BB4', iconTone: 'light' },
  laravel: { hex: '#FF2D20', iconTone: 'light' },
  java: { hex: '#000000', iconTone: 'light' },
  spring: { hex: '#6DB33F', iconTone: 'light' },
  kotlin: { hex: '#7F52FF', iconTone: 'light' },
  swift: { hex: '#F05138', iconTone: 'light' },
  go: { hex: '#00ADD8', iconTone: 'light' },
  rust: { hex: '#000000', iconTone: 'light' },
  c: { hex: '#A8B9CC', iconTone: 'light' },
  cpp: { hex: '#00599C', iconTone: 'light' },
  csharp: { hex: '#239120', iconTone: 'light' },
  dotnet: { hex: '#512BD4', iconTone: 'light' },
  dart: { hex: '#0175C2', iconTone: 'light' },
  flutter: { hex: '#02569B', iconTone: 'light' },
  android: { hex: '#3DDC84', iconTone: 'light' },
  apple: { hex: '#000000', iconTone: 'light' },
  linux: { hex: '#FCC624', iconTone: 'dark' },
  ubuntu: { hex: '#E95420', iconTone: 'light' },
  debian: { hex: '#A81D33', iconTone: 'light' },
  graphql: { hex: '#E10098', iconTone: 'light' },
  redis: { hex: '#FF4438', iconTone: 'light' },
  mysql: { hex: '#4479A1', iconTone: 'light' },
  sqlite: { hex: '#003B57', iconTone: 'light' },
  supabase: { hex: '#3FCF8E', iconTone: 'light' },
  firebase: { hex: '#DD2C00', iconTone: 'light' },
  aws: { hex: '#FF9900', iconTone: 'light' },
  googleCloud: { hex: '#4285F4', iconTone: 'light' },
  azure: { hex: '#0078D4', iconTone: 'light' },
  cloudflare: { hex: '#F38020', iconTone: 'light' },
  vercel: { hex: '#000000', iconTone: 'light' },
  netlify: { hex: '#00C7B7', iconTone: 'light' },
  kubernetes: { hex: '#326CE5', iconTone: 'light' },
  terraform: { hex: '#844FBA', iconTone: 'light' },
  ansible: { hex: '#EE0000', iconTone: 'light' },
  jenkins: { hex: '#D24939', iconTone: 'light' },
  githubActions: { hex: '#2088FF', iconTone: 'light' },
  gitlab: { hex: '#FC6D26', iconTone: 'light' },
  npm: { hex: '#CB3837', iconTone: 'light' },
  pnpm: { hex: '#F69220', iconTone: 'light' },
  yarn: { hex: '#2C8EBB', iconTone: 'light' },
  bun: { hex: '#000000', iconTone: 'light' },
  deno: { hex: '#000000', iconTone: 'light' },
  bash: { hex: '#4EAA25', iconTone: 'light' },
  vscode: { hex: '#007ACC', iconTone: 'light' },
  figma: { hex: '#F24E1E', iconTone: 'light' },
}
