import { Database, Terminal } from 'lucide-react'
import type { ComponentType } from 'react'
import {
  SiAmazonaws,
  SiAndroid,
  SiAngular,
  SiAnsible,
  SiApple,
  SiAstro,
  SiBun,
  SiC,
  SiCloudflare,
  SiCplusplus,
  SiCsharp,
  SiCss3,
  SiDart,
  SiDebian,
  SiDeno,
  SiDjango,
  SiDocker,
  SiDotnet,
  SiExpress,
  SiFastapi,
  SiFigma,
  SiFirebase,
  SiFlask,
  SiFlutter,
  SiGit,
  SiGithub,
  SiGithubactions,
  SiGitlab,
  SiGnubash,
  SiGo,
  SiGooglecloud,
  SiGraphql,
  SiHtml5,
  SiJavascript,
  SiJenkins,
  SiKotlin,
  SiKubernetes,
  SiLaravel,
  SiLinux,
  SiMicrosoftazure,
  SiMongodb,
  SiMysql,
  SiNestjs,
  SiNetlify,
  SiNextdotjs,
  SiNodedotjs,
  SiNpm,
  SiNuxtdotjs,
  SiOpenjdk,
  SiPhp,
  SiPnpm,
  SiPostgresql,
  SiPython,
  SiReact,
  SiRedis,
  SiRemix,
  SiRuby,
  SiRubyonrails,
  SiRust,
  SiSolid,
  SiSpring,
  SiSqlite,
  SiSupabase,
  SiSvelte,
  SiSwift,
  SiTailwindcss,
  SiTerraform,
  SiTypescript,
  SiUbuntu,
  SiVercel,
  SiVisualstudiocode,
  SiVite,
  SiVuedotjs,
  SiYarn,
} from 'react-icons/si'

type TechnologyIconMap = Record<
  string,
  { label: string; Icon: ComponentType<{ className?: string }> }
>

export const technologyIcons: TechnologyIconMap = {
  javascript: { label: 'JavaScript', Icon: SiJavascript },
  typescript: { label: 'TypeScript', Icon: SiTypescript },
  html5: { label: 'HTML5', Icon: SiHtml5 },
  css3: { label: 'CSS3', Icon: SiCss3 },
  react: { label: 'React', Icon: SiReact },
  vue: { label: 'Vue.js', Icon: SiVuedotjs },
  angular: { label: 'Angular', Icon: SiAngular },
  node: { label: 'Node.js', Icon: SiNodedotjs },
  python: { label: 'Python', Icon: SiPython },
  docker: { label: 'Docker', Icon: SiDocker },
  git: { label: 'Git', Icon: SiGit },
  github: { label: 'GitHub', Icon: SiGithub },
  postgresql: { label: 'PostgreSQL', Icon: SiPostgresql },
  mongodb: { label: 'MongoDB', Icon: SiMongodb },
  tailwind: { label: 'Tailwind CSS', Icon: SiTailwindcss },
  nextjs: { label: 'Next.js', Icon: SiNextdotjs },
  vite: { label: 'Vite', Icon: SiVite },
  svelte: { label: 'Svelte', Icon: SiSvelte },
  solid: { label: 'SolidJS', Icon: SiSolid },
  astro: { label: 'Astro', Icon: SiAstro },
  remix: { label: 'Remix', Icon: SiRemix },
  nuxt: { label: 'Nuxt', Icon: SiNuxtdotjs },
  nestjs: { label: 'NestJS', Icon: SiNestjs },
  express: { label: 'Express', Icon: SiExpress },
  django: { label: 'Django', Icon: SiDjango },
  flask: { label: 'Flask', Icon: SiFlask },
  fastapi: { label: 'FastAPI', Icon: SiFastapi },
  ruby: { label: 'Ruby', Icon: SiRuby },
  rails: { label: 'Ruby on Rails', Icon: SiRubyonrails },
  php: { label: 'PHP', Icon: SiPhp },
  laravel: { label: 'Laravel', Icon: SiLaravel },
  java: { label: 'Java', Icon: SiOpenjdk },
  spring: { label: 'Spring', Icon: SiSpring },
  kotlin: { label: 'Kotlin', Icon: SiKotlin },
  swift: { label: 'Swift', Icon: SiSwift },
  go: { label: 'Go', Icon: SiGo },
  rust: { label: 'Rust', Icon: SiRust },
  c: { label: 'C', Icon: SiC },
  cpp: { label: 'C++', Icon: SiCplusplus },
  csharp: { label: 'C#', Icon: SiCsharp },
  dotnet: { label: '.NET', Icon: SiDotnet },
  dart: { label: 'Dart', Icon: SiDart },
  flutter: { label: 'Flutter', Icon: SiFlutter },
  android: { label: 'Android', Icon: SiAndroid },
  apple: { label: 'Apple', Icon: SiApple },
  linux: { label: 'Linux', Icon: SiLinux },
  ubuntu: { label: 'Ubuntu', Icon: SiUbuntu },
  debian: { label: 'Debian', Icon: SiDebian },
  graphql: { label: 'GraphQL', Icon: SiGraphql },
  redis: { label: 'Redis', Icon: SiRedis },
  mysql: { label: 'MySQL', Icon: SiMysql },
  sqlite: { label: 'SQLite', Icon: SiSqlite },
  // SQL (el lenguaje estándar) no tiene un logo de marca propio — a
  // diferencia de postgresql/mysql/sqlite arriba, que sí son motores
  // concretos. Mismo patrón ya usado para "terminal" (lucide genérico,
  // no un logo de marca).
  sql: { label: 'SQL', Icon: Database },
  supabase: { label: 'Supabase', Icon: SiSupabase },
  firebase: { label: 'Firebase', Icon: SiFirebase },
  aws: { label: 'AWS', Icon: SiAmazonaws },
  googleCloud: { label: 'Google Cloud', Icon: SiGooglecloud },
  azure: { label: 'Microsoft Azure', Icon: SiMicrosoftazure },
  cloudflare: { label: 'Cloudflare', Icon: SiCloudflare },
  vercel: { label: 'Vercel', Icon: SiVercel },
  netlify: { label: 'Netlify', Icon: SiNetlify },
  kubernetes: { label: 'Kubernetes', Icon: SiKubernetes },
  terraform: { label: 'Terraform', Icon: SiTerraform },
  ansible: { label: 'Ansible', Icon: SiAnsible },
  jenkins: { label: 'Jenkins', Icon: SiJenkins },
  githubActions: { label: 'GitHub Actions', Icon: SiGithubactions },
  gitlab: { label: 'GitLab', Icon: SiGitlab },
  npm: { label: 'npm', Icon: SiNpm },
  pnpm: { label: 'pnpm', Icon: SiPnpm },
  yarn: { label: 'Yarn', Icon: SiYarn },
  bun: { label: 'Bun', Icon: SiBun },
  deno: { label: 'Deno', Icon: SiDeno },
  bash: { label: 'Bash', Icon: SiGnubash },
  vscode: { label: 'Visual Studio Code', Icon: SiVisualstudiocode },
  figma: { label: 'Figma', Icon: SiFigma },
  terminal: { label: 'Terminal', Icon: Terminal },
}
